# Generated by Django 5.2.12 on 2026-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Медицинская услуга',
                'verbose_name_plural': 'Медицинские услуги',
                'ordering': ['specialty__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('not_paid', 'Не оплачено'), ('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('free', 'Бесплатно')], default='not_paid', max_length=20, verbose_name='Статус оплаты')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Перевод'), ('insurance', 'Страховая'), ('free', 'Бесплатно')], max_length=20, verbose_name='Способ оплаты')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
