# Generated by Django 5.2.12 on 2026-04-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('outpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outpatient.specialty', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='outpatient.appointment', verbose_name='Прием'),
        ),
    ]
