# Generated by Django 5.2.12 on 2026-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='allow_repeat',
            field=models.BooleanField(default=True, verbose_name='Можно назначать повторно'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='daily_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если ограничения нет.', null=True, verbose_name='Ограничение услуги в день'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='requires_referral',
            field=models.BooleanField(default=False, verbose_name='Требует направление'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='service_type',
            field=models.CharField(choices=[('primary_consultation', 'Первичная консультация'), ('repeat_consultation', 'Повторная консультация'), ('ultrasound', 'УЗИ'), ('procedure', 'Процедура'), ('laboratory', 'Лабораторное исследование'), ('other', 'Другое')], default='primary_consultation', max_length=40, verbose_name='Тип услуги'),
        ),
    ]
