# Generated by Django 5.2.12 on 2026-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_ward_inpatientadmission_bed_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientprocedure',
            name='is_written_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionexecution',
            name='is_written_off',
            field=models.BooleanField(default=False),
        ),
    ]
