# Generated by Django 5.2.12 on 2026-04-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0005_inpatientprocedure_is_written_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionexecution',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionexecution',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='inpatient.prescription'),
        ),
    ]
