# Generated by Django 5.2.12 on 2026-04-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0006_prescriptionexecution_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatientprocedure',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='inpatientprocedure',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='inpatient.inpatientadmission'),
        ),
        migrations.AlterField(
            model_name='inpatientprocedure',
            name='procedure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inpatientprocedure',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inpatientprocedure',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
