# Generated by Django 5.2.12 on 2026-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item_type',
            field=models.CharField(blank=True, choices=[('material', 'Материал'), ('medication', 'Лекарство')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
