# Generated by Django 5.2.12 on 2026-04-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceMaterial',
        ),
    ]
