# Generated by Django 5.2.12 on 2026-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField()),
                ('complaints', models.TextField(blank=True)),
                ('anamnesis', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'Создан'), ('in_progress', 'В процессе'), ('done', 'Завершён')], default='new', max_length=20)),
            ],
        ),
    ]
