# Generated by Django 5.2.12 on 2026-04-18 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО врача')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(verbose_name='Жалобы пациента')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Анамнез')),
                ('objective_status', models.TextField(blank=True, verbose_name='Объективный статус')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='План лечения')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('outcome', models.CharField(choices=[('consultation_completed', 'Консультация завершена'), ('need_examination', 'Назначено обследование'), ('hospitalization_required', 'Требуется госпитализация'), ('repeat_visit', 'Назначен повторный прием'), ('referral', 'Направлен к другому специалисту')], max_length=40, verbose_name='Итог приема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('primary', 'Первичное обращение'), ('repeat', 'Повторное обращение'), ('consultation', 'Консультация'), ('examination', 'Обследование'), ('hospitalization', 'Госпитализация'), ('emergency', 'Экстренное обращение')], max_length=30, verbose_name='Тип обращения')),
                ('reason', models.TextField(verbose_name='Причина обращения')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('waiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('sent_to_doctor', 'Направлен к врачу'), ('in_progress', 'На приеме'), ('need_examination', 'Требуется обследование'), ('hospitalization_required', 'Требуется госпитализация'), ('repeat_visit_required', 'Требуется повторный прием'), ('referred', 'Направлен к другому специалисту'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='created', max_length=40, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Обращение пациента',
                'verbose_name_plural': 'Обращения пациентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название специальности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата приема')),
                ('appointment_time', models.TimeField(verbose_name='Время приема')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('waiting', 'Ожидает приема'), ('in_progress', 'Идет прием'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='waiting', max_length=30, verbose_name='Статус')),
                ('registrar_comment', models.TextField(blank=True, verbose_name='Комментарий регистратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.medicalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
