# Generated by Django 5.2.12 on 2026-04-19 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код МКБ-10')),
                ('name', models.CharField(max_length=500, verbose_name='Название диагноза')),
                ('external_url', models.URLField(blank=True, verbose_name='Ссылка на классификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Диагноз МКБ-10',
                'verbose_name_plural': 'Диагнозы МКБ-10',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='anamnesis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='objective_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Запрещена отмена/изменение'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выполнения услуги'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Услугу выполнил'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='anamnesis_disease',
            field=models.TextField(blank=True, verbose_name='Анамнез болезни'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='anamnesis_life',
            field=models.TextField(blank=True, verbose_name='Анамнез жизни'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinical_diagnosis',
            field=models.TextField(blank=True, verbose_name='Клинический диагноз'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_reasoning',
            field=models.TextField(blank=True, verbose_name='Обоснование диагноза'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='gynecological_anamnesis',
            field=models.TextField(blank=True, verbose_name='Гинекологический анамнез'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='preliminary_diagnosis',
            field=models.TextField(blank=True, verbose_name='Предварительный диагноз'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status_praesens',
            field=models.TextField(blank=True, verbose_name='Общее состояние / Status praesens'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinical_icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records', to='outpatient.icd10diagnosis', verbose_name='МКБ-10 клинического диагноза'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='preliminary_icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_records', to='outpatient.icd10diagnosis', verbose_name='МКБ-10 предварительного диагноза'),
        ),
    ]
