# Generated by Django 5.2.12 on 2026-04-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_servicematerial'),
        ('outpatient', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatient.outpatientvisit')),
            ],
        ),
    ]
