# Generated by Django 5.2.12 on 2026-04-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_medicalservice_allow_repeat_and_more'),
        ('outpatient', '0003_icd10diagnosis_remove_medicalrecord_anamnesis_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина направления')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('appointment_created', 'Прием создан'), ('cancelled', 'Отменено')], default='created', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_referral', to='outpatient.appointment', verbose_name='Созданный прием')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Направил')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
                ('source_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_referrals', to='outpatient.appointment', verbose_name='Исходный прием')),
                ('target_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outpatient.doctor', verbose_name='Врач')),
                ('target_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.medicalservice', verbose_name='Услуга')),
                ('target_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outpatient.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Направление к специалисту',
                'verbose_name_plural': 'Направления к специалистам',
                'ordering': ['-created_at'],
            },
        ),
    ]
