# Generated by Django 5.2.12 on 2026-04-20 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_medicalservice_allow_repeat_and_more'),
        ('outpatient', '0004_specialistreferral'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('waiting', 'Ожидает приема'), ('in_progress', 'Идет прием'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('reserved', 'Забронирован')], default='waiting', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('waiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('sent_to_doctor', 'Направлен к врачу'), ('in_progress', 'На приеме'), ('need_examination', 'Требуется обследование'), ('hospitalization_required', 'Требуется госпитализация'), ('repeat_visit_required', 'Требуется повторный прием'), ('referred', 'Направлен к другому специалисту'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('reserved', 'Забронировано')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_active_doctor_appointment_slot'),
        ),
    ]
