# Generated by Django 5.2.12 on 2026-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0005_alter_appointment_status_alter_patientvisit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10diagnosis',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='icd10diagnosis',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
    ]
