# Generated by Django 5.2.12 on 2026-05-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0006_alter_icd10diagnosis_external_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticStudyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование исследования')),
                ('kind', models.CharField(choices=[('lab', 'Лабораторное'), ('instrumental', 'Инструментальное')], max_length=20, verbose_name='Тип исследования')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('reference_range', models.CharField(blank=True, max_length=255, verbose_name='Референсные значения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Справочник исследований',
                'verbose_name_plural': 'Справочник исследований',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticStudyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=255, verbose_name='Результат')),
                ('conclusion', models.TextField(blank=True, verbose_name='Заключение')),
                ('include_in_reasoning', models.BooleanField(default=True, verbose_name='Включать в обоснование')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_results', to='outpatient.appointment', verbose_name='Прием')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_study_results', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outpatient.diagnosticstudycatalog', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Результат исследования',
                'verbose_name_plural': 'Результаты исследований',
                'ordering': ['id'],
            },
        ),
    ]
