# Generated by Django 5.2.12 on 2026-05-29 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatient', '0007_diagnosticstudycatalog_diagnosticstudyresult'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата госпитализации')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Отделение')),
                ('ward', models.CharField(blank=True, max_length=50, verbose_name='Палата')),
                ('bed', models.CharField(blank=True, max_length=50, verbose_name='Койка')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('admitted', 'Госпитализирован'), ('discharged', 'Выписан'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('admission_reason', models.TextField(blank=True, verbose_name='Основание для госпитализации')),
                ('complaints', models.TextField(blank=True, verbose_name='Жалобы при поступлении')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Анамнез')),
                ('objective_status', models.TextField(blank=True, verbose_name='Объективный статус')),
                ('diagnosis_text', models.TextField(blank=True, verbose_name='Диагноз текстом')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='План обследования и лечения')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации из амбулаторного приема')),
                ('study_summary', models.TextField(blank=True, verbose_name='Данные исследований до госпитализации')),
                ('daily_notes', models.TextField(blank=True, verbose_name='Дневниковые записи')),
                ('discharge_summary', models.TextField(blank=True, verbose_name='Выписной эпикриз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outpatient.doctor', verbose_name='Направивший врач')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inpatient_records', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outpatient.icd10diagnosis', verbose_name='Диагноз МКБ-10')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Пациент')),
                ('source_appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inpatient_record', to='outpatient.appointment', verbose_name='Амбулаторный прием-основание')),
            ],
            options={
                'verbose_name': 'Стационарная карта',
                'verbose_name_plural': 'Стационарные карты',
                'ordering': ['-admission_date', '-created_at'],
            },
        ),
    ]
