# Generated by Django 5.2.12 on 2026-04-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('inpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='inpatient_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inpatient.inpatientadmission'),
        ),
    ]
